id = "discord-presence"
name = "Discord Presence"
version = "0.2.3"
schema_version = 1
description = "Presence for your beautiful discord account :)"
repository = "https://github.com/xhyrom/zed-discord-presence"
authors = ["Jozef Steinhübl <contact@xhyrom.dev>"]
themes = []
icon_themes = []
languages = []

[lib]
kind = "Rust"
version = "0.0.6"

[grammars]

[language_servers.discord_presence]
languages = ["ActionScript", "Ada", "Agda", "Aiken", "Amber", "Ansible", "AsciiDoc", "Assembly", "Astro", "AWK", "Shell Script", "Beancount", "Bend", "bitbake", "Blade", "Blueprint", "BQN", "Brainfuck", "C3", "Caddyfile", "Cadence", "Cairo", "Cap'n Proto", "Cedar", "CFEngine", "cfhtml", "cfml", "cfscript", "Clojure", "COBOL", "CONL", "Cooklang", "Cpp2", "Crystal", "ECR", "CSV", "Gherkin", "CUE", "Curry", "Cylc", "Cypher", "Cython", "D", "D2", "Dafny", "Dart", "DBML", "devicetree", "Docker Compose", "Dockerfile", "DuckyScript", "Earthfile", "EDI X12", "EJS", "Elisp", "Elm", "Handlebars", "env", "Exograph", "Firebase Rules", "Fish", "FlatBuffers", "Fortran", "Fountain", "FSharp", "GDScript", "Godot Resource", "Gemini", "Diff", "Git Attributes", "Git Commit", "Git Config", "Git Ignore", "Git Rebase", "Gleam", "Go Sum", "GraphQL", "DOT", "Gren", "Groovy", "GROQ", "Haml", "Hare", "Haxe", "Helm", "HLSL", "http", "Hurl", "iCal", "Idris2", "IPKG", "Inform 6", "ini", "ISLE", "Janet", "Java", "Properties", "Jinja2", "Jsonnet", "Julia", "Just", "Kconfig", "Kdl", "Kotlin", "BibTeX", "LaTeX", "Ledger", "LESS", "LilyPond", "LilyPond Scheme", "Liquid", "LOG", "Lox", "Luau", "Make", "MATLAB", "", "Move", "move", "Navi", "Navi Stream", "CMake", "Nginx", "Nickel", "Nim", "Nim Format String", "Nix", "Noir", "Nu", "Dune", "OCaml Interface", "OCaml", "Odin", "OMNeT++ MSG", "OMNeT++ NED", "OpenSCAD", "Org", "Pact", "Path of Exile Filter", "Perl", "Perm", "Pest", "PHP", "PHPDoc", "pica200", "Pkl", "PlantUML", "Animation.txt", "Pdxinfo", "PowerShell", "Prisma", "Prolog", "Pug", "QML", "QuakeC", "R", "Racket", "Rainbow CSV", "Rainbow TSV", "RCL", "rego", "ReScript", "Rhai", "Roc", "RON", "RPM Spec", "reST", "ERB", "RBS", "Ruby", "SageMath", "Scala", "Scheme", "SCSS", "Simula", "Slim", "Smithy", "Standard ML", "Snakemake", "Solidity", "Sourcepawn", "SQL", "SSH Config", "Stan", "bazelrc", "Starlark", "Strace", "Surreal Query Language", "Svelte", "Swift", "Templ", "Tera (CSS)", "Tera (HTML)", "Tera (JSON)", "Tera (TOML)", "Tera (YAML)", "Tera", "tmux", "Tree-sitter Query", "Twig", "Typst", "Unison", "V", "Vala", "vCard", "Vento", "Verilog", "VHDL", "VHS", "VRL", "Vue.js", "WebAssembly Text Format", "WDL", "Wgsl", "whkd", "WIT", "XML", "Yara", "ziggy-schema", "ziggy", "C", "C++", "CSS", "Go", "Go Mod", "Go Work", "JavaScript", "JSDoc", "JSON", "JSONC", "Markdown-Inline", "Markdown", "Python", "Regex", "Rust", "TSX", "TypeScript", "YAML", "CSharp", "Elixir", "HEEX", "Erlang", "GLSL", "Haskell", "HTML", "Lua", "Proto", "PureScript", "HCL", "Terraform Vars", "Terraform", "TOML", "Uiua", "Zig", "edge"]

[language_servers.discord_presence.language_ids]
Groovy = "groovy"
ISLE = "isle"
AWK = "awk"
Roc = "roc"
GraphQL = "graphql"
cfscript = "cfscript"
Kdl = "kdl"
PHP = "php"
Ledger = "ledger"
Svelte = "svelte"
LilyPond = "lilypond"
GROQ = "groq"
Properties = "properties"
Perl = "perl"
Cadence = "cadence"
Cooklang = "cooklang"
Uiua = "uiua"
Scala = "scala"
LaTeX = "latex"
Blueprint = "blueprint"
Jsonnet = "jsonnet"
YAML = "yaml"
cfml = "cfml"
Diff = "diff"
CONL = "conl"
"OCaml Interface" = "ocaml-interface"
LOG = "log"
COBOL = "cobol"
GDScript = "gdscript"
Luau = "luau"
Lua = "lua"
D2 = "d2"
Kconfig = "kconfig"
MATLAB = "matlab"
ziggy = "ziggy"
Dockerfile = "dockerfile"
CFEngine = "cfengine"
Amber = "amber"
Cairo = "cairo"
Dart = "dart"
move = "move"
"Standard ML" = "sml"
Aiken = "aiken"
Vala = "vala"
VHS = "vhs"
Unison = "unison"
RCL = "rcl"
SageMath = "sage"
Smithy = "smithy"
FlatBuffers = "flatbuffers"
AsciiDoc = "asciidoc"
IPKG = "ipkg"
vCard = "vcard"
"Tera (HTML)" = "tera-html"
Cpp2 = "cpp2"
Exograph = "exograph"
LESS = "less"
D = "d"
Stan = "stan"
iCal = "vcard"
TypeScript = "typescript"
http = "http"
BibTeX = "bibtex"
bitbake = "bitbake"
JavaScript = "javascript"
JSONC = "jsonc"
"Godot Resource" = "godot_resource"
Haxe = "haxe"
Dafny = "dafny"
"Tera (YAML)" = "tera-yaml"
Brainfuck = "brainfuck"
RON = "ron"
Snakemake = "snakemake"
Pug = "pug"
rego = "rego"
ReScript = "rescript"
Racket = "racket"
Cylc = "cylc"
Gherkin = "gherkin"
Ruby = "ruby"
Caddyfile = "caddyfile"
WDL = "wdl"
QML = "qml"
Assembly = "asm"
Crystal = "crystal"
Terraform = "terraform"
Cypher = "cypher"
TSX = "tsx"
"WebAssembly Text Format" = "wat"
"EDI X12" = "edi-x12"
Swift = "swift"
"Tree-sitter Query" = "query"
"Tera (CSS)" = "tera-css"
Zig = "zig"
edge = "edge"
Prisma = "prisma"
"Git Ignore" = "gitignore"
"Firebase Rules" = "firebase-security-rules"
OCaml = "ocaml"
QuakeC = "quakec"
Noir = "noir"
PlantUML = "plantuml"
CMake = "cmake"
RBS = "rbs"
VHDL = "vhdl"
"LilyPond Scheme" = "lilypond_scheme"
Nickel = "nickel"
tmux = "tmux"
Helm = "helm"
"SSH Config" = "ssh_config"
PHPDoc = "phpdoc"
"Git Config" = "gitconfig"
"RPM Spec" = "rpmspec"
Pest = "pest"
Just = "just"
EJS = "ejs"
PowerShell = "powershell"
Prolog = "prolog"
Erlang = "erlang"
TOML = "toml"
Verilog = "verilog"
Kotlin = "kotlin"
V = "v"
HLSL = "hlsl"
Agda = "agda"
Ansible = "ansible"
Julia = "julia"
Navi = "navi"
SCSS = "scss"
Elisp = "elisp"
Markdown = "markdown"
"Vue.js" = "vue"
Gemini = "gemini"
Tera = "tera"
Elixir = "elixir"
Cython = "cython"
Pkl = "pkl"
"Docker Compose" = "docker-compose"
Dune = "dune"
XML = "xml"
Beancount = "beancount"
"Git Rebase" = "gitrebase"
WIT = "wit"
C = "c"
Hare = "hare"
BQN = "BQN"
Go = "go"
CUE = "cue"
Templ = "templ"
"Terraform Vars" = "terraform-vars"
Blade = "blade"
Jinja2 = "jinja2"
C3 = "c3"
DuckyScript = "duckyscript"
devicetree = "devicetree"
Pact = "pact"
DOT = "dot"
JSON = "json"
"OMNeT++ NED" = "ned"
"Surreal Query Language" = "surql"
DBML = "dbml"
R = "r"
Haml = "haml"
"Navi Stream" = "navi_stream"
ini = "ini"
Strace = "strace"
"C++" = "cpp"
Nim = "nim"
Nu = "nu"
Odin = "odin"
reST = "rst"
Markdown-Inline = "markdown-inline"
Scheme = "scheme"
Nginx = "nginx"
CSharp = "csharp"
Java = "java"
Nix = "nix"
Handlebars = "glimmer"
CSV = "csv"
Org = "org"
"Animation.txt" = "animationtxt"
Simula = "simula"
bazelrc = "bazelrc"
Earthfile = "earthfile"
GLSL = "glsl"
"Cap'n Proto" = "capnp"
Regex = "regex"
cfhtml = "cfhtml"
Astro = "astro"
Hurl = "hurl"
Python = "python"
JSDoc = "jsdoc"
Solidity = "solidity"
HEEX = "heex"
Janet = "janet"
Gren = "gren"
"Nim Format String" = "nim_format_string"
"Go Mod" = "gomod"
"Rainbow TSV" = "tsv"
"Go Work" = "gowork"
"OMNeT++ MSG" = "msg"
Typst = "typst"
Yara = "yara"
ERB = "erb"
Pdxinfo = "pdxinfo"
CSS = "css"
Bend = "bend"
Fortran = "fortran"
Elm = "elm"
Vento = "vento"
"Inform 6" = "inform6"
Twig = "twig"
Sourcepawn = "sourcepawn"
VRL = "vrl"
pica200 = "pica200"
Proto = "proto"
Rust = "rust"
Ada = "ada"
"Rainbow CSV" = "csv"
PureScript = "purescript"
Starlark = "starlark"
Haskell = "haskell"
Fish = "fish"
ActionScript = "actionscript"
ECR = "ecr"
Lox = "lox"
Clojure = "clojure"
ziggy-schema = "ziggy-schema"
Move = "move"
SQL = "sql"
"Tera (TOML)" = "tera-toml"
Curry = "curry"
Slim = "slim"
Cedar = "cedar"
"Tera (JSON)" = "tera-json"
HTML = "html"
"Git Attributes" = "gitattributes"
Gleam = "gleam"
env = "env"
Make = "make"
"Shell Script" = "bash"
Rhai = "rhai"
Perm = "perm"
"Go Sum" = "gosum"
Fountain = "fountain"
Idris2 = "idris2"
"Path of Exile Filter" = "poe-filter"
Liquid = "liquid"
OpenSCAD = "openscad"
"Git Commit" = "gitcommit"
HCL = "hcl"
whkd = "whkd"
FSharp = "fsharp"
Wgsl = "wgsl"
"" = "mermaid"

[context_servers]

[slash_commands]

[indexed_docs_providers]
