"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color8)\
$os\
$username\
[](bg:color1 fg:color8)\
$directory\
[](fg:color1 bg:color9)\
$git_branch\
$git_status\
[](fg:color9 bg:color8)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color8 bg:color1)\
$docker_context\
$conda\
$pixi\
[](fg:color1 bg:color9)\
$time\
[ ](fg:color9)\
$line_break$character"""

palette = 'colors'

[palettes.colors]
color1 = '{{colors.primary_fixed_dim.default.hex}}'
color2 = '{{colors.on_primary.default.hex}}'
color3 = '{{colors.on_surface_variant.default.hex}}'
color4 = '{{colors.surface_container.default.hex}}'
color5 = '{{colors.on_primary.default.hex}}'
color6 = '{{colors.surface_dim.default.hex}}'
color7 = '{{colors.surface.default.hex}}'
color8 = '{{colors.primary.default.hex}}'
color9 = '{{colors.tertiary.default.hex}}'

[os]
disabled = false
style = "bg:color8 fg:color2"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color8 fg:color2"
style_root = "bg:color8 fg:color2"
format = '[ $user ]($style)'

[directory]
style = "bg:color1 fg:color2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color9"
format = '[[ $symbol $branch ](fg:color2 bg:color9)]($style)'

[git_status]
style = "bg:color9"
format = '[[($all_status$ahead_behind )](fg:color2 bg:color9)]($style)'

[nodejs]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[bun]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[c]
symbol = " "
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[cpp]
symbol = " "
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[rust]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[golang]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[php]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[java]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[kotlin]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[haskell]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[python]
symbol = ""
style = "bg:color8"
format = '[[ $symbol( $version) ](fg:color2 bg:color8)]($style)'

[docker_context]
symbol = ""
style = "bg:color1"
format = '[[ $symbol( $context) ](fg:color2 bg:color1)]($style)'

[conda]
style = "bg:color1"
format = '[[ $symbol( $environment) ](fg:color2 bg:color1)]($style)'

[pixi]
style = "bg:color1"
format = '[[ $symbol( $version)( $environment) ](fg:color2 bg:color1)]($style)'

# [time]
# disabled = false
# time_format = "%R"
# style = "bg:color9"
# format = '[[  $time ](fg:color2 bg:color9)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color8)'
error_symbol = '[](bold fg:color9)'
vimcmd_symbol = '[](bold fg:color8)'
vimcmd_replace_one_symbol = '[](bold fg:color1)'
vimcmd_replace_symbol = '[](bold fg:color1)'
vimcmd_visual_symbol = '[](bold fg:color9)'
