# ==========================
# Hyprland source files
# ==========================

source = ~/.config/hypr/hyprbindings.conf
source = ~/.config/hypr/hyprenvs.conf
source = ~/.config/hypr/hyprinput.conf
source = ~/.config/hypr/hyprlooknfeel.conf
source = ~/.config/hypr/hyprmonitor.conf
source = ~/.config/hypr/hyprwindows.conf
source = ~/.config/hypr/hyprautostart.conf
# source = ~/.config/hypr/hypridle.conf
# source = ~/.config/hypr/hyprlock.conf
