# ==========================
# Hyprland autostart
# ==========================

# Session environment for systemd/dbus/portals
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE

# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# Notifications
exec-once = mako

# Idle/lock handling
exec-once = hypridle

# OSD
exec-once = swayosd-server

# Clipboard
# exec-once = cliphist wipe && rm -rf ~/.cache/cliphist_thumbs/*
exec-once = wl-paste --type text --watch cliphist store 30
exec-once = wl-paste --type image --watch cliphist store 30
exec-once = wl-clip-persist --clipboard regular

# Wallpaper and theme
exec-once = awww-daemon

# Bar
exec-once = waybar

#
exec-once = clipse -listen
