# ==========================
# Hyprland autostart
# ==========================

# Session environment for systemd/dbus/portals
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE

# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# Notifications
exec-once = mako

# Idle/lock handling
exec-once = hypridle

# OSD
exec-once = swayosd-server

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-clip-persist --clipboard regular

# Wallpaper and theme
exec-once = awww-daemon
# exec-once = ~/.config/scripts/restore-wallpaper-theme.sh

# Bar
exec-once = waybar

# GTK theme preference
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark' && gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
