# yazi.toml
[mgr]
show_hidden = true
# ratio = [ 0, 2, 5 ]

[[open.prepend_rules]]
url = "$HOME/.config/wallpapers/*"
use = [ "set-wallpaper", "open", "reveal" ]

[opener]
set-wallpaper = [
  { run = '/home/hyprash/.config/scripts/wallpaper.sh "$@"', orphan = true, for = "unix", desc = "Set as wallpaper" }
]
edit = [
  { run = "nvim \"$@\"", block = true, for = "unix" },
]
image = [
  { run = 'feh "$@"', orphan = true, desc = "Open Image", for = "unix" },
]
video = [
  { run = 'mpv "$@"', orphan = true, desc = "Play Video", for = "unix" },
]
