# yazi.toml
[mgr]
show_hidden = true

[opener]
edit = [
  { run = "nvim \"$@\"", block = true, for = "unix" },
]
image = [
  { run = 'feh "$@"', orphan = true, desc = "Open Image", for = "linux" },
]
video = [
  { run = 'mpv "$@"', orphan = true, desc = "Play Video", for = "linux" },
]
