format = """
[](fg:blue)\
$os\
$username\
[](fg:blue bg:green)\
$directory\
[](fg:green bg:black)\
$git_branch\
$git_status\
[](fg:black)\
$line_break\
$character"""

[os]
disabled = false
style = "bg:blue fg:black"
format = "[$symbol]($style)"

[os.symbols]
Arch = "  "

[username]
show_always = true
style_user = "bg:blue fg:black"
style_root = "bg:red fg:black"
format = "[$user ]($style)"
disabled = false

[directory]
style = "bg:green fg:black"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Scripts" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:black fg:blue"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:black fg:red"
format = "[$all_status$ahead_behind ]($style)"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
disabled = false

[cmd_duration]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[lua]
disabled = true

[golang]
disabled = true
