general {
    # Uses your existing hyprlock app, and prevents it from accidentally launching twice
    lock_cmd = pidof hyprlock || hyprlock
    # Wakes your monitors up properly when you unlock
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    # Time in seconds (300 seconds = 5 minutes)
    timeout = 300
    # What to do when the time runs out
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0  # save state and turn off keyboard backlight
    on-resume = brightnessctl -rd '*::kbd_backlight'         # restore keyboard backlight
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # or hyprctl dispatch dpms on # screen on when activity is detected
}
