-- ==========================
-- Hyprland look and feel
-- ==========================

-- matugen colors (generated by matugen into colors.lua alongside colors.conf)
local colors = require("colors")

-- ================ performance ================

-- disable fancy but battery hungry effects
hl.config({
    decoration = {
        blur = { enabled = false },
        shadow = { enabled = false },
    },
    debug = {
        vfr = true, -- lower the amount of sent frames when nothing is happening on-screen.
    },
})

-- ================ general ================
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 5,
        border_size = 0,
        col = {
            active_border   = colors.primary,
            inactive_border = colors.on_primary_container,
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
        -- there is also master and scrolling
    },
})

-- ================ decoration ================
hl.config({
    decoration = {
        rounding = 16,
        shadow = {
            enabled = false,
            range = 2,
            render_power = 3,
            color = colors.primary,
        },
        blur = {
            enabled = true,
            size = 2,
            passes = 2,
            special = true,
            -- brightness = 0.60, -- this and contrast can make the background darker
            -- contrast = 0.75,
        },
    },
})

-- ================ groups ================
hl.config({
    group = {
        col = {
            border_active         = colors.primary,
            border_inactive        = colors.on_primary_container,
            border_locked_active   = -1,
            border_locked_inactive = -1,
        },
        groupbar = {
            font_size   = 12,
            font_family = "monospace",
            font_weight_active   = "ultraheavy",
            font_weight_inactive = "normal",

            indicator_height = 0,
            indicator_gap    = 5,
            height   = 22,
            gaps_in  = 5,
            gaps_out = 0,

            text_color          = "rgb(ffffff)",
            text_color_inactive = "rgba(ffffff90)",
            col = {
                active   = "rgba(00000040)",
                inactive = "rgba(00000020)",
            },

            gradients                 = true,
            gradient_rounding         = 0,
            gradient_round_only_edges = false,
        },
    },
})

-- ================ Animations ================
-- require("hyprAnimations.ash")

hl.config({ animations = { enabled = true } })

hl.curve("wind",   { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("winIn",  { type = "bezier", points = { {0.1, 1.1},  {0.1, 1.1} } })
hl.curve("winOut", { type = "bezier", points = { {0.3, -0.3}, {0, 1} } })
hl.curve("liner",  { type = "bezier", points = { {1, 1},      {1, 1} } })

hl.animation({ leaf = "windows",     enabled = true, speed = 6,  bezier = "wind",   style = "slide" })
hl.animation({ leaf = "windowsIn",   enabled = true, speed = 6,  bezier = "winIn",  style = "slide" })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 5,  bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5,  bezier = "wind",   style = "slide" })
hl.animation({ leaf = "border",      enabled = true, speed = 1,  bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner",  style = "once" })
hl.animation({ leaf = "fade",        enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,  bezier = "wind" })


-- ================ dwindle ================
-- NOTE: dwindle:pseudotile was removed in Hyprland 0.55 (it did nothing).
-- Pseudotiling is enabled via the SUPER + P bind (hl.dsp.window.pseudo()) below.
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
        force_split = 2,       -- Always split on the right
    },
})

-- ================ misc ================
hl.config({
    misc = {
        disable_hyprland_logo     = true,
        disable_splash_rendering  = true,
        focus_on_activate         = true,
        anr_missed_pings          = 3,
        on_focus_under_fullscreen = 1,
    },
    cursor = {
        hide_on_key_press        = true,
        warp_on_change_workspace = 1,
    },
    binds = {
        hide_special_on_workspace_change = true,
    },
})

