# ==========================
# Hyprland autostart
# ==========================

exec-once = bash -c 'awww daemon & sleep 2 && if [ ! -f ~/.config/.wall_initialized ]; then ~/.config/scripts/wallpaper.sh ~/.config/wallpapers/wallpaper13.png && touch ~/.config/.wall_initialized && hyprctl reload; fi'

# Session environment for systemd/dbus/portals
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_TYPE

# gtk
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark''

# Waybar
exec-once = waybar

# Authentication agent
exec-once = systemctl --user start hyprpolkitagent

# Notifications
exec-once = mako

# clipboard history
exec-once = wl-paste --type text --watch cliphist store -max-items 50
exec-once = wl-paste --type image --watch cliphist store -max-items 50
exec-once = wl-clip-persist --clipboard regular

# Idle/lock handling
exec-once = hypridle

# OSD
exec-once = swayosd-server

# Wallpaper and theme
exec-once = awww-daemon

# cursor
# exec-once = hyprctl setcursor catppuccin-mocha-dark-cursors 24
