"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_surface0)\
$os\
$username\
[](bg:color_peach fg:color_surface0)\
$directory\
[](fg:color_peach bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_teal bg:color_blue)\
$docker_context\
[](fg:color_blue bg:color_purple)\
$time\
[ ](fg:color_purple)\
$line_break$character"""

# Call the dynamic Matugen palette
palette = 'matugen'

[palettes.matugen]
color_surface0 = "{{colors.surface_container_high.default.hex}}"
color_text = "{{colors.on_surface.default.hex}}"
color_peach = "{{colors.primary.default.hex}}"
color_mantle = "{{colors.on_primary.default.hex}}"
color_green = "{{colors.secondary.default.hex}}"
color_base = "{{colors.on_secondary.default.hex}}"
color_teal = "{{colors.tertiary.default.hex}}"
color_blue = "{{colors.primary_fixed_dim.default.hex}}"
color_purple = "{{colors.secondary_fixed_dim.default.hex}}"
color_red = "{{colors.error.default.hex}}"
color_lavender = "{{colors.tertiary_fixed.default.hex}}"

[os]
disabled = false
style = "bg:color_surface0 fg:color_text"

[os.symbols]
arch = "󰣇"

[username]
show_always = true
style_user = "bg:color_surface0 fg:color_text"
style_root = "bg:color_surface0 fg:color_text"
format = '[ $user ]($style)'

[directory]
style = "fg:color_mantle bg:color_peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol $branch ](fg:color_base bg:color_green)]($style)'

[git_status]
style = "bg:color_teal"
format = '[[($all_status$ahead_behind )](fg:color_base bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[c]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[rust]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[golang]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[php]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[java]
symbol = " "
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[kotlin]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[haskell]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[python]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol( $version) ](fg:color_base bg:color_teal)]($style)'

[docker_context]
symbol = ""
style = "bg:color_mantle"
format = '[[ $symbol( $context) ](fg:color_base bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_lavender)'
