"$schema" = 'https://starship.rs/config-schema.json'

# Call the dynamic Matugen palette
palette = 'colors'

[palettes.colors]
surface0 = '{{colors.surface_container_high.default.hex}}'
text = '{{colors.on_surface.default.hex}}'
peach = '{{colors.primary.default.hex}}'
mantle = '{{colors.on_primary.default.hex}}'
green = '{{colors.secondary.default.hex}}'
base = '{{colors.on_secondary.default.hex}}'
teal = '{{colors.tertiary.default.hex}}'
blue = '{{colors.primary_fixed_dim.default.hex}}'
purple = '{{colors.secondary_fixed_dim.default.hex}}'
red = '{{colors.error.default.hex}}'

format = """
[](fg:purple)\
$os\
$username\
[](bg:red fg:purple)\
$directory\
[](bg:peach fg:red)\
$git_branch\
$git_status\
[](bg:blue fg:peach)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$maven\
$nodejs\
$bun\
$nim\
$rust\
$scala\
[](bg:teal fg:blue)\
$docker_context\
[](bg:green fg:teal)\
$time\
[ ](fg:green)\
\n$character"""

[username]
show_always = true
style_user = "bg:purple fg:text"
style_root = "bg:purple fg:text"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:purple fg:text"
disabled = true

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Mint = "󰣭"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Arch = "󰣇"
Debian = "󰣚"

[directory]
style = "bg:red fg:text"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[cpp]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:teal fg:base"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:peach fg:mantle"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:peach fg:mantle"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[maven]
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[bun]
symbol = ""
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue fg:base"
format = '[ $symbol ($version) ]($style)'
