wallpaper {
    monitor = DP-1
    path = ~/.config/wallpapers/wallpaper13.png
    fit_mode = cover
}

echo "preload = /home/ash/wallpapers/wallpapers/03.jpg" > ~/.config/hypr/hyprpaper.conf
echo "wallpaper = ,/home/ash/wallpapers/wallpapers/03.jpg" >> ~/.config/hypr/hyprpaper.conf
echo "splash = false" >> ~/.config/hypr/hyprpaper.conf
