# ==========================
# Hyprland source files
# ==========================

source = ~/.config/hypr/hyprbindings.conf
source = ~/.config/hypr/hyprenvs.conf
source = ~/.config/hypr/hyprinput.conf
#source = ~/.config/hypr/hyprlauncher.conf
source = ~/.config/hypr/hyprlock.conf
source = ~/.config/hypr/hyprlook.conf
source = ~/.config/hypr/hyprmonitor.conf
source = ~/.config/hypr/hyprwindows.conf
source = ~/.config/hypr/hyprpaper.conf
source = ~/.config/hypr/colors.conf
